/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Testimonials = {
  _id: string;
  _type: "testimonials";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  text?: string;
  author?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type News = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  date?: string;
  showOnHomepage?: boolean;
  summary?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & MainImage)
  | ({
      _key: string;
    } & Youtube)
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type LogoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "logo";
};

export type Quiz2021 = {
  _id: string;
  _type: "quiz2021";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sectionTitle?: string;
  bannerImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  welcomeText?: BlockContent;
  startButton?: string;
  titleSponsors?: string;
  logosSponsors?: Array<
    {
      _key: string;
    } & LogoReference
  >;
  questions?: Array<
    | ({
        _key: string;
      } & InputTypeQuestion)
    | ({
        _key: string;
      } & SelectTypeQuestion)
    | ({
        _key: string;
      } & AssociationTypeQuestion)
  >;
  submitText?: BlockContent;
};

export type DepartmentReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "department";
};

export type QuizByDepartment = {
  _id: string;
  _type: "quizByDepartment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  department?: DepartmentReference;
  question?: string;
  answers?: Array<string>;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type PressKit = {
  _id: string;
  _type: "pressKit";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type ContactDepartment = {
  _id: string;
  _type: "contactDepartment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  department?: DepartmentReference;
  name?: string;
  phone?: string;
  email?: string;
  url?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageContent?: Array<
    | ({
        _key: string;
      } & EditorialPageBlock)
    | ({
        _key: string;
      } & ContactPageBlock)
    | ({
        _key: string;
      } & CovidPageBlock)
    | ({
        _key: string;
      } & ScolairesPageBlock)
    | ({
        _key: string;
      } & MultimediaPageBlock)
    | ({
        _key: string;
      } & EventsIndexPageBlock)
    | ({
        _key: string;
      } & MentionsLegalesPageBlock)
    | ({
        _key: string;
      } & HomePageBlock)
    | ({
        _key: string;
      } & FeaturedBlock)
    | ({
        _key: string;
      } & VillageBlock)
    | ({
        _key: string;
      } & FooterBlock)
    | ({
        _key: string;
      } & Quiz21ConditionsPageBlock)
    | ({
        _key: string;
      } & QuestionnairePageBlock)
  >;
  pageName?: string;
};

export type OnlineEvent = {
  _id: string;
  _type: "onlineEvent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  description?: BlockContent;
  mediaUrl?: string;
  bookingRequired?: boolean;
  bookingRecommanded?: boolean;
};

export type VillageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "village";
};

export type ProjectOwnerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "projectOwner";
};

export type ThemeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "theme";
};

export type FormatReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "format";
};

export type AudienceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "audience";
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  village?: Array<
    {
      _key: string;
    } & VillageReference
  >;
  featured?: boolean;
  education?: boolean;
  eventCanceled?: boolean;
  description?: BlockContent;
  projectOwners?: Array<
    {
      _key: string;
    } & ProjectOwnerReference
  >;
  department?: DepartmentReference;
  address?: string;
  timeSlots?: Array<
    {
      _key: string;
    } & TimeSlot
  >;
  timeSlotsPhoneContact?: string;
  informationEmail?: string;
  informationPhone?: string;
  bookingRequired?: boolean;
  bookingRecommanded?: boolean;
  bookingEmail?: string;
  bookingPhone?: string;
  bookingWebsite?: string;
  theme?: Array<
    {
      _key: string;
    } & ThemeReference
  >;
  format?: Array<
    {
      _key: string;
    } & FormatReference
  >;
  audience?: Array<
    {
      _key: string;
    } & AudienceReference
  >;
  audienceCustom?: AudienceCustom;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  eventImageCredits?: string;
};

export type AudienceCustom = {
  _type: "audienceCustom";
  from?: number;
  to?: number;
};

export type ProjectOwner = {
  _id: string;
  _type: "projectOwner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  website?: string;
  facebook?: string;
};

export type Route = {
  _id: string;
  _type: "route";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  hide?: boolean;
  link?: string;
  order?: number;
};

export type Logo = {
  _id: string;
  _type: "logo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  partners?: Array<
    {
      _key: string;
    } & DepartmentReference
  >;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  width?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  startDate?: string;
  endDate?: string;
  showCovid?: boolean;
  showQuiz?: boolean;
  instagramHashtag?: string;
  instagramLink?: string;
  openGraph?: OpenGraph;
  videoLink?: string;
  videoPlaceholder?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  fdsLogoWhite?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  fdsLogoBlack?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type OpenGraph = {
  _type: "openGraph";
  title?: string;
  description?: string;
  keywords?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Ambassador = {
  _id: string;
  _type: "ambassador";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  testimony?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  video?: string;
};

export type AdageMappings = {
  _id: string;
  _type: "adageMappings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  themeChoices?: Array<
    {
      _key: string;
    } & ThemeMapping
  >;
  formatChoices?: Array<
    {
      _key: string;
    } & FormatMapping
  >;
  departmentChoices?: Array<
    {
      _key: string;
    } & DepartmentMapping
  >;
  villageChoices?: Array<
    {
      _key: string;
    } & VillageMapping
  >;
  nomEtablissement?: string;
  departement?: string;
  titre?: string;
  formats?: string;
  description?: string;
  themes?: string;
  typePublic?: string;
  village?: string;
  adresse?: string;
  audience?: string;
  audienceCustomFrom?: string;
  audienceCustomTo?: string;
  bookingRequired?: string;
  bookingEmail?: string;
  bookingPhone?: string;
  informationPhone?: string;
  informationEmail?: string;
  idAdage?: string;
};

export type VillageMapping = {
  _type: "villageMapping";
  label?: string;
  destination?: VillageReference;
};

export type Village = {
  _id: string;
  _type: "village";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  scolaire?: boolean;
  grandPublic?: boolean;
  eventCanceled?: boolean;
  description?: BlockContent;
  department?: DepartmentReference;
  address?: string;
  timeSlots?: Array<
    {
      _key: string;
    } & TimeSlot
  >;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type DepartmentMapping = {
  _type: "departmentMapping";
  label?: string;
  destination?: DepartmentReference;
};

export type Department = {
  _id: string;
  _type: "department";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
};

export type FormatMapping = {
  _type: "formatMapping";
  label?: string;
  destination?: FormatReference;
};

export type Format = {
  _id: string;
  _type: "format";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  formatIcon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type AudienceMapping = {
  _type: "audienceMapping";
  label?: string;
  destination?: AudienceReference;
};

export type Audience = {
  _id: string;
  _type: "audience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  audienceEducation?: boolean;
  age?: number;
};

export type ThemeMapping = {
  _type: "themeMapping";
  label?: string;
  destination?: ThemeReference;
};

export type Theme = {
  _id: string;
  _type: "theme";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
};

export type DocumentField = {
  _type: "documentField";
  name?: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  description?: string;
};

export type QuestionnairePageBlock = {
  _type: "questionnairePageBlock";
  title?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  intro?: string;
  documentsTitle?: string;
  documents?: Array<
    {
      _key: string;
    } & DocumentField
  >;
  additionalInfos?: string;
  faq?: Array<
    {
      _key: string;
    } & FaqQuestion
  >;
};

export type FaqQuestion = {
  _type: "faqQuestion";
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type AssociationTypeOption = {
  _type: "associationTypeOption";
  title?: string;
  picture?: MainImage;
  answer?: string;
};

export type SelectTypeOption = {
  _type: "selectTypeOption";
  title?: string;
  answer?: boolean;
  description?: string;
  picture?: MainImage;
};

export type AssociationTypeQuestion = {
  _type: "associationTypeQuestion";
  questionType?: string;
  title?: string;
  description?: BlockContent;
  options?: Array<
    {
      _key: string;
    } & AssociationTypeOption
  >;
  answerDetails?: BlockContent;
};

export type MainImage = {
  _type: "mainImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type SelectTypeQuestion = {
  _type: "selectTypeQuestion";
  questionType?: string;
  title?: string;
  description?: BlockContent;
  options?: Array<
    {
      _key: string;
    } & SelectTypeOption
  >;
  answerDetails?: BlockContent;
};

export type InputTypeQuestion = {
  _type: "inputTypeQuestion";
  questionType?: string;
  title?: string;
  description?: BlockContent;
  picture?: Array<
    {
      _key: string;
    } & MainImage
  >;
  answer?: string;
  answerDetails?: BlockContent;
};

export type PressContact = {
  _type: "pressContact";
  name?: string;
  phone?: string;
  email?: string;
};

export type TimeSlot = {
  _type: "timeSlot";
  startDate?: string;
  startTime?: string;
  endDate?: string;
  endTime?: string;
};

export type Quiz21ConditionsPageBlock = {
  _type: "quiz21ConditionsPageBlock";
  topTitle?: string;
  contentBlock?: BlockContent;
};

export type HomePageBlock = {
  _type: "homePageBlock";
  heroButton?: string;
  showProgrammeButtons?: boolean;
  heroUrl?: string;
  leftLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  leftLogoWidth?: number;
  showRedCircle?: boolean;
  rightLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  rightLogoWidth?: number;
  hideNews?: boolean;
  showFavorites?: boolean;
  featuresTitle?: string;
  features?: Array<
    {
      _key: string;
    } & FeatureDesc
  >;
  featuresButton?: string;
  keyFigures?: Array<
    {
      _key: string;
    } & KeyFigure
  >;
  instagramTitle?: string;
};

export type MentionsLegalesPageBlock = {
  _type: "mentionsLegalesPageBlock";
  topTitle?: string;
  contentBlock?: BlockContent;
};

export type VillageBlock = {
  _type: "villageBlock";
  villageTitle?: string;
  villageContent?: string;
};

export type FeaturedBlock = {
  _type: "featuredBlock";
  featuredTitle?: string;
  featuredContent?: string;
};

export type FooterBlock = {
  _type: "footerBlock";
  logosRankTop?: Array<
    {
      _key: string;
    } & LogoReference
  >;
  logosRankBottom?: Array<
    {
      _key: string;
    } & LogoReference
  >;
  instagramLinkFooter?: string;
};

export type ScolairesPageBlock = {
  _type: "scolairesPageBlock";
  topTitle?: string;
  partnersTitle?: string;
  logosList?: Array<
    {
      _key: string;
    } & LogoReference
  >;
};

export type CovidPageBlock = {
  _type: "covidPageBlock";
  topTitle?: string;
  contentBlock?: BlockContent;
};

export type EventsIndexPageBlock = {
  _type: "eventsIndexPageBlock";
  topTitle?: string;
  partnersTitle?: string;
};

export type MultimediaPageBlock = {
  _type: "multimediaPageBlock";
  topTitle?: string;
  contentBlock?: BlockContent;
};

export type ContactPageBlock = {
  _type: "contactPageBlock";
  topTitle?: string;
  topContent?: BlockContent;
  pressTitle?: string;
  contactTitle?: string;
  pressContact?: PressContact;
  resourceTitle?: string;
};

export type EditorialPageBlock = {
  _type: "editorialPageBlock";
  topTitle?: string;
  topContent?: BlockContent;
  previousEditionsTitle?: string;
  previousEditions?: Array<
    {
      _key: string;
    } & MainImage
  >;
  partnersTitle?: string;
  partnersContent?: BlockContent;
  organizersTitle?: string;
  organizers?: Array<
    {
      _key: string;
    } & MainImage
  >;
  partners?: Array<
    {
      _key: string;
    } & MainImage
  >;
  contactTitle?: string;
  contactContent?: BlockContent;
  contactPressTitle?: string;
  pressContact?: PressContact;
};

export type FeatureDesc = {
  _type: "featureDesc";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  feature?: BlockContent;
};

export type Youtube = {
  _type: "youtube";
  url?: string;
};

export type KeyFigure = {
  _type: "keyFigure";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  number?: string;
  description?: string;
};

export type RichDate = {
  _type: "richDate";
  local?: string;
  utc?: string;
  timezone?: string;
  offset?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Testimonials
  | SanityImageAssetReference
  | News
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | LogoReference
  | Quiz2021
  | DepartmentReference
  | QuizByDepartment
  | SanityFileAssetReference
  | PressKit
  | ContactDepartment
  | Page
  | OnlineEvent
  | VillageReference
  | ProjectOwnerReference
  | ThemeReference
  | FormatReference
  | AudienceReference
  | Event
  | AudienceCustom
  | ProjectOwner
  | Route
  | Logo
  | SiteSettings
  | OpenGraph
  | Ambassador
  | AdageMappings
  | VillageMapping
  | Village
  | DepartmentMapping
  | Department
  | FormatMapping
  | Format
  | AudienceMapping
  | Audience
  | ThemeMapping
  | Theme
  | DocumentField
  | QuestionnairePageBlock
  | FaqQuestion
  | AssociationTypeOption
  | SelectTypeOption
  | AssociationTypeQuestion
  | MainImage
  | SelectTypeQuestion
  | InputTypeQuestion
  | PressContact
  | TimeSlot
  | Quiz21ConditionsPageBlock
  | HomePageBlock
  | MentionsLegalesPageBlock
  | VillageBlock
  | FeaturedBlock
  | FooterBlock
  | ScolairesPageBlock
  | CovidPageBlock
  | EventsIndexPageBlock
  | MultimediaPageBlock
  | ContactPageBlock
  | EditorialPageBlock
  | FeatureDesc
  | Youtube
  | KeyFigure
  | RichDate
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;
